const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Plugins.Model3D,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Behaviors.LOS,
		C3.Behaviors.custom,
		C3.Plugins.Light3D,
		C3.Behaviors.Billboard,
		C3.Behaviors.Follow,
		C3.Plugins.Text,
		C3.Behaviors.skymen_RadialProgress,
		C3.Behaviors.Rotate,
		C3.Plugins.Json,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Timer,
		C3.Behaviors.MoveTo,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.ExitGames_PhotonRealtime,
		C3.Plugins.Sparsha_FirebaseSDK,
		C3.Plugins.Sparsha_FirebaseAuth,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase,
		C3.Plugins.AJAX,
		C3.Behaviors.scrollto,
		C3.Plugins.Custom_LayerInteractivity,
		C3.Behaviors.Orbit,
		C3.Plugins.NinePatch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.ClaudeUI_WindowScrollPanel,
		C3.Plugins.ClaudeUI_VideoCanvas,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Camera3D.Acts.SetFieldOfView,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Light3D.Cnds.CompareInstanceVar,
		C3.Plugins.Light3D.Acts.SetPos3D,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Light3D.Acts.SetRotationEuler,
		C3.Plugins.Camera3D.Exps.CameraYRotation,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Cnds.HasPointerLock,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetZ,
		C3.Plugins.Sprite.Exps.Z,
		C3.Plugins.Model3D.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.SetListenerOrientation,
		C3.Plugins.Camera3D.Exps.UpX,
		C3.Plugins.Camera3D.Exps.UpY,
		C3.Plugins.Camera3D.Exps.UpZ,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.ExitGames_PhotonRealtime.Exps.MyActorNr,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Model3D.Acts.SetMeshObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.onActorLeave,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.ExitGames_PhotonRealtime.Exps.ActorNr,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.ExitGames_PhotonRealtime.Acts.disconnect,
		C3.Plugins.ExitGames_PhotonRealtime.Acts.raiseEvent,
		C3.Plugins.Model3D.Acts.SetAnimation,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.onEvent,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.ExitGames_PhotonRealtime.Exps.EventData,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Camera3D.Exps.LayerToLayerX,
		C3.Plugins.Camera3D.Exps.LayerToLayerY,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.skymen_RadialProgress.Acts.SetValue,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Json.Cnds.OnParseSuccess,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTableFromJSON,
		C3.Plugins.Json.Exps.GetAsBeautifiedString,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.AdvancedRandom.Exps.WeightedByName,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Model3D.Acts.SetInstanceVar,
		C3.Plugins.Model3D.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Model3D.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Model3D.Acts.SetAngle,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Model3D.Cnds.OnCreated,
		C3.Plugins.Model3D.Exps.X,
		C3.Plugins.Model3D.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Behaviors.Pathfinding.Exps.MaxSpeed,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Cnds.IsClockwiseFrom,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Shape3D.Cnds.PickDistance,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Behaviors.Tween.Acts.TweenThreeProperties,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.Shape3D.Exps.Depth,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Model3D.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.RegenerateMap,
		C3.Plugins.Sprite.Cnds.OnInstanceSignal,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.Stop,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.InstanceSignal,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Model3D.Acts.SetZ,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Model3D.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Model3D.Acts.SetTowardPosition,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Mouse.Cnds.OnPointerLocked,
		C3.Plugins.Mouse.Cnds.OnPointerUnlocked,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Model3D.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Model3D.Acts.SetOpacity,
		C3.Plugins.Shape3D.Exps.Z,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Model3D.Cnds.PickDistance,
		C3.Plugins.Model3D.Acts.SetCollisions,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Mouse.Acts.ReleasePointerLock,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.isJoinedToRoom,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.NinePatch.Cnds.PickParent,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Cnds.LayerNameExists,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerForceOwnTexture,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Behaviors.ClaudeUI_WindowScrollPanel.Acts.SetMask,
		C3.Plugins.System.Acts.MoveLayer,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.InstanceSignal,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.TiledBg.Exps.LayerName,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.NinePatch.Cnds.PickTopBottom,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Cnds.OnInstanceSignal,
		C3.Plugins.Sparsha_FirebaseAuth.Cnds.IsSignedIn,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.System.Exps.len,
		C3.Plugins.ExitGames_PhotonRealtime.Acts.connect,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.isConnectedToMaster,
		C3.Plugins.ExitGames_PhotonRealtime.Acts.joinRoom,
		C3.Plugins.ExitGames_PhotonRealtime.Acts.setMyRoomMaxPlayers,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.onJoinRoom,
		C3.Plugins.ExitGames_PhotonRealtime.Exps.ActorCount,
		C3.Plugins.Sparsha_FirebaseAuth.Exps.picURL,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.onError,
		C3.Plugins.ExitGames_PhotonRealtime.Cnds.onDisconnected,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.SimpleWriteData,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Acts.AdvancedReadData,
		C3.Plugins.Sparsha_FirebaseAuth.Exps.userID,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Cnds.OnAdvTrigger,
		C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Exps.readValue,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.Sparsha_FirebaseAuth.Acts.PopupOauth,
		C3.Plugins.Sparsha_FirebaseAuth.Acts.SignOut,
		C3.Plugins.Sparsha_FirebaseAuth.Cnds.OnSignedOut,
		C3.Plugins.Sparsha_FirebaseAuth.Exps.userName,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Floor1: 0},
	{Floor2: 0},
	{Roof1: 0},
	{Floors: 0},
	{Floor3: 0},
	{Floor4: 0},
	{Floor5: 0},
	{Floor7: 0},
	{Floor6: 0},
	{Floor8: 0},
	{Floor9: 0},
	{Floor10: 0},
	{Floor11: 0},
	{Floor12: 0},
	{Floor13: 0},
	{Difference: 0},
	{Wall1: 0},
	{Sine: 0},
	{Wall: 0},
	{WindowType: 0},
	{Broken: 0},
	{"3D_Window": 0},
	{Destroyng: 0},
	{BreakableWall: 0},
	{Wall2: 0},
	{Price: 0},
	{ObjectType: 0},
	{VendingMachine: 0},
	{texture_Wall1: 0},
	{texture_Wall2: 0},
	{texture_Wall3: 0},
	{texture_Wall4: 0},
	{texture_Wall5: 0},
	{texture_Wall6: 0},
	{texture_Windows1: 0},
	{texture_Windows2: 0},
	{texture_Windows3: 0},
	{texture_Windows4: 0},
	{texture_Windows5: 0},
	{texture_Windows6: 0},
	{texture_Wall10: 0},
	{texture_Wall11: 0},
	{texture_Wall13: 0},
	{texture_Wall14: 0},
	{texture_Wall15: 0},
	{texture_Wall7: 0},
	{texture_Wall8: 0},
	{texture_Wall9: 0},
	{texture_Wall12: 0},
	{Vending_sprite1: 0},
	{Vending_sprite2: 0},
	{VendingBorder_sprite: 0},
	{Vending_sprite3: 0},
	{texture_Wall16: 0},
	{texture_Wall17: 0},
	{texture_Wall18: 0},
	{texture_Wall19: 0},
	{texture_Wall20: 0},
	{Vending_sprite4: 0},
	{Decorations: 0},
	{Pantaleone: 0},
	{Active: 0},
	{Tween: 0},
	{Carpet: 0},
	{Trees: 0},
	{FakeWall: 0},
	{Banners: 0},
	{PaintingName: 0},
	{name: 0},
	{PaintingType: 0},
	{Paintings: 0},
	{PlayerOrder: 0},
	{PlayerNr: 0},
	{Targettable: 0},
	{Alive: 0},
	{ActualAnimation: 0},
	{LockAnimation: 0},
	{Physics: 0},
	{LineOfSight: 0},
	{LineOfSight2: 0},
	{"3D_Player": 0},
	{CameraState: 0},
	{PeerSpectator: 0},
	{Personalizzato: 0},
	{playerview: 0},
	{"3D_Camera": 0},
	{"3D_PlayerRange": 0},
	{Distintion: 0},
	{PlayerLight: 0},
	{PlayerModel: 0},
	{Faces: 0},
	{ObjectID: 0},
	{Billboard: 0},
	{Follow: 0},
	{Item: 0},
	{Number: 0},
	{PlayerModel1: 0},
	{PlayerModel2: 0},
	{PlayerModel3: 0},
	{PlayerModel4: 0},
	{Type: 0},
	{Faces1: 0},
	{Faces2: 0},
	{Faces3: 0},
	{Faces4: 0},
	{Skin: 0},
	{Hand: 0},
	{Name: 0},
	{"3D_Peer": 0},
	{Item1: 0},
	{Item2: 0},
	{Item3: 0},
	{Item4: 0},
	{Body1: 0},
	{Body2: 0},
	{Body3: 0},
	{Body4: 0},
	{PlayerName: 0},
	{musiczone: 0},
	{volume: 0},
	{MusicZones: 0},
	{ZoneType: 0},
	{CumulativeZones: 0},
	{TouchZones: 0},
	{SlotNumber: 0},
	{Selected: 0},
	{StartY: 0},
	{UtilValue: 0},
	{InventorySlot: 0},
	{InventorySlotY: 0},
	{HandAnimation: 0},
	{state: 0},
	{Time: 0},
	{MaxTime: 0},
	{RadialProgress: 0},
	{LoadingBar: 0},
	{HUD_Interferences: 0},
	{type: 0},
	{itemdescription: 0},
	{ScreenText: 0},
	{Puntatore: 0},
	{Screen_CumulativeText: 0},
	{AlertText: 0},
	{HUD_SfondoMenu: 0},
	{HUD_SfondoMenuPattern: 0},
	{MouseAnimation: 0},
	{ButtonType: 0},
	{Menu_button: 0},
	{StartX: 0},
	{Menu_Text: 0},
	{SelectionPoint: 0},
	{DebugMenu: 0},
	{ModelPC: 0},
	{HUD_Information: 0},
	{StaminaType: 0},
	{StartLeinght: 0},
	{Stamine: 0},
	{Rotate: 0},
	{CacioMagico: 0},
	{InteractText: 0},
	{ItemDescriptions: 0},
	{Pool: 0},
	{Couple: 0},
	{ItemGenerator: 0},
	{ItemPool: 0},
	{ItemPoolTables: 0},
	{Model_caciocavallo: 0},
	{Placeable: 0},
	{PlaceablePreview: 0},
	{Model_glue: 0},
	{Model_mantle: 0},
	{attivo: 0},
	{portal1: 0},
	{portal2: 0},
	{Model_capricorno: 0},
	{harpooncorda: 0},
	{Model_trappola: 0},
	{EnemyID: 0},
	{ContactKill: 0},
	{Jumpscare: 0},
	{DebugX: 0},
	{DebugY: 0},
	{State: 0},
	{LocationX: 0},
	{LocationY: 0},
	{StepTime: 0},
	{WaitingTime: 0},
	{LostDistance: 0},
	{Access: 0},
	{FindPath: 0},
	{Pathfinding: 0},
	{Timer: 0},
	{Gustavo: 0},
	{M_Gustavo: 0},
	{Path_Gustavo: 0},
	{Fresco: 0},
	{M_Fresco: 0},
	{Path_Fresco: 0},
	{Path_MrMorte: 0},
	{MrMorte: 0},
	{M_MrMorte: 0},
	{Pickable: 0},
	{Canerino: 0},
	{M_Canerino: 0},
	{Path_Canerino: 0},
	{Pane: 0},
	{Path_Pane: 0},
	{M_Pane: 0},
	{PeerUID: 0},
	{Nano: 0},
	{M_Nano: 0},
	{Path_Nano: 0},
	{Manzone: 0},
	{M_Manzone: 0},
	{Path_Manzone: 0},
	{M_Pantaleone: 0},
	{JumpscareSprite: 0},
	{DipintoTexture: 0},
	{Modello_cornice: 0},
	{DoorID: 0},
	{DoorStartAngle: 0},
	{door1: 0},
	{direction: 0},
	{Puzzle: 0},
	{Breakable: 0},
	{TempoChiusura: 0},
	{DoorsCollision: 0},
	{PuzzleLock: 0},
	{Elevator: 0},
	{ElevatorDoor: 0},
	{InvisibleWall: 0},
	{MobilePainting: 0},
	{NpcType: 0},
	{Interactable: 0},
	{Value1: 0},
	{NpcContainer: 0},
	{FollowVisual: 0},
	{Npc_body: 0},
	{NpcDialogue: 0},
	{CoordX: 0},
	{CoordY: 0},
	{DialogueBox: 0},
	{NpcPositions: 0},
	{HoverTypes: 0},
	{HT_SlotGraphics: 0},
	{HT_SlotLever: 0},
	{Order: 0},
	{HT_Slots: 0},
	{HT_SlotSkip: 0},
	{Ricalco: 0},
	{MoveTo: 0},
	{StoricTitles: 0},
	{TitlesDeco: 0},
	{EndingBackground: 0},
	{Camera3D: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{PhotonRealtime: 0},
	{FirebaseSDK: 0},
	{FirebaseAuthBasic: 0},
	{FirebaseRDBasic: 0},
	{AJAX: 0},
	{MonitorBorder: 0},
	{MoitorEffect: 0},
	{PC_Background: 0},
	{PC_Cursor: 0},
	{PC_Actionbar: 0},
	{EmojiBoard: 0},
	{AppType: 0},
	{AppIcon: 0},
	{AppDownloadState: 0},
	{ScrollTo: 0},
	{PC_Cam: 0},
	{LayerInteractivity: 0},
	{Window_Notes_Text: 0},
	{StartAnimation: 0},
	{Testo: 0},
	{websitelink: 0},
	{DifferenzaParticolare: 0},
	{DifferenzaParticolare_2: 0},
	{Orbit: 0},
	{InternetElementsDeco: 0},
	{ChangeFrameDeco: 0},
	{websiteText: 0},
	{Window: 0},
	{DragDrop: 0},
	{WindowCore: 0},
	{WindowButton: 0},
	{WindowBackground: 0},
	{WindowIcon: 0},
	{WindowName: 0},
	{WindowScrollPanel: 0},
	{NomePagina: 0},
	{LinkButtons: 0},
	{WindowMaskPanel: 0},
	{VideoCanvas: 0},
	{window_Internal_button: 0},
	{WindowDeco: 0},
	{MPCF: 0},
	{Description: 0},
	{BuyPanel: 0},
	{BuyButton: 0},
	{ShopJson: 0},
	{GameButton: 0},
	{BarType: 0},
	{HUD_overlay: 0},
	{MenuText: 0},
	{ButtonAnimation: 0},
	{Animation: 0},
	{MenuButton: 0},
	{PlayerNumber: 0},
	{AccountImage: 0},
	{InteractiveText: 0},
	{Character: 0},
	{CharacterSelector: 0},
	{VideoPanel: 0},
	{Sfida: 0},
	{SfidaText: 0},
	{SfidaCompletata: 0},
	{PlayersInfo: 0},
	{Transition: 0},
	{BlackScreen: 0},
	{Ordine: 0},
	{AccenzionePc: 0},
	{GameSave: 0},
	{ResocontoValue: 0},
	{Floors_and_roofs: 0},
	{Walls: 0},
	{Structure: 0},
	{pathfinding_obstacles: 0},
	{Enemies: 0},
	{Doors: 0},
	{ItemModels_Placed: 0},
	{particular: 0},
	{Peer: 0},
	{Distinction: 0},
	{DistinctionModel: 0},
	{Dx: 0},
	{Dy: 0},
	{Movex: 0},
	{Movey: 0},
	{NearestX: 0},
	{NearestY: 0},
	{Sensibilità: 0},
	{Stamina: 0},
	{PlayerSpeed: 0},
	{PlayerSpeedrun: 0},
	{PlayerSpeedwalk: 0},
	{Movements: 0},
	{PlayerAlive: 0},
	{PlayerState: 0},
	{CameraHeight: 0},
	{CameraFov: 0},
	{GameState: 0},
	{FadeOut: 0},
	{Layout_Name: 0},
	{Plustime: 0},
	{Sound: 0},
	{randomnumber: 0},
	{LoopINDX: 0},
	{NewAnimation: 0},
	{GameDeath: 0},
	{Jumpscaretype: 0},
	{deathplayers: 0},
	{Money: 0},
	{Username: 0},
	{RoomCode: 0},
	{HOST: 0},
	{FinishCondition: 0},
	{HandItem: 0},
	{InventorySlots: 0},
	{SelectedSlot: 0},
	{Posx: 0},
	{Posy: 0},
	{PosxY: 0},
	{Direzione: 0},
	{MyX: 0},
	{MyY: 0},
	{DoorUID: 0},
	{PuzzlePieces: 0},
	{WindowX: 0},
	{WindowY: 0},
	{playersin: 0},
	{MenuOpen: 0},
	{CanOpenMenu: 0},
	{ItemX: 0},
	{ItemY: 0},
	{itemType: 0},
	{Local: 0},
	{ActorNr: 0},
	{DistanceRendering: 0},
	{MinigameName: 0},
	{wincondition: 0},
	{UnlockBergamaschio: 0},
	{BordoDestraX: 0},
	{BordoSinistraX: 0},
	{BordoAltoY: 0},
	{BordoBassoY: 0},
	{WindowUID: 0},
	{ButtonUID: 0},
	{Cardiollari: 0},
	{cooldown: 0},
	{Window_Width: 0},
	{Window_Height: 0},
	{AppUID: 0},
	{New_WindowScrollPanel_UID: 0},
	{WindowScrollPanel_Y: 0},
	{PageToOpen: 0},
	{PageToDestroy_UID: 0},
	{CodeBreaker: 0},
	{posx: 0},
	{posy: 0},
	{posx1: 0},
	{posx2: 0},
	{posy1: 0},
	{posy2: 0},
	{TotDigitalCardus: 0},
	{Language: 0},
	{GameState_Name: 0}
];

self.InstanceType = {
	Floor1: class extends self.ITiledBackgroundInstance {},
	Floor2: class extends self.ITiledBackgroundInstance {},
	Roof1: class extends self.ITiledBackgroundInstance {},
	Floors: class extends self.I3DShapeInstance {},
	Floor3: class extends self.ITiledBackgroundInstance {},
	Floor4: class extends self.ITiledBackgroundInstance {},
	Floor5: class extends self.ITiledBackgroundInstance {},
	Floor7: class extends self.ITiledBackgroundInstance {},
	Floor6: class extends self.ITiledBackgroundInstance {},
	Floor8: class extends self.ITiledBackgroundInstance {},
	Floor9: class extends self.ITiledBackgroundInstance {},
	Floor10: class extends self.ITiledBackgroundInstance {},
	Floor11: class extends self.ITiledBackgroundInstance {},
	Floor12: class extends self.ITiledBackgroundInstance {},
	Floor13: class extends self.ITiledBackgroundInstance {},
	Wall1: class extends self.I3DShapeInstance {},
	Wall: class extends self.I3DShapeInstance {},
	_3D_Window: class extends self.I3DShapeInstance {},
	BreakableWall: class extends self.I3DShapeInstance {},
	Wall2: class extends self.I3DShapeInstance {},
	VendingMachine: class extends self.I3DShapeInstance {},
	texture_Wall1: class extends self.ITiledBackgroundInstance {},
	texture_Wall2: class extends self.ITiledBackgroundInstance {},
	texture_Wall3: class extends self.ITiledBackgroundInstance {},
	texture_Wall4: class extends self.ITiledBackgroundInstance {},
	texture_Wall5: class extends self.ITiledBackgroundInstance {},
	texture_Wall6: class extends self.ITiledBackgroundInstance {},
	texture_Windows1: class extends self.ISpriteInstance {},
	texture_Windows2: class extends self.ISpriteInstance {},
	texture_Windows3: class extends self.ISpriteInstance {},
	texture_Windows4: class extends self.ISpriteInstance {},
	texture_Windows5: class extends self.ISpriteInstance {},
	texture_Windows6: class extends self.ISpriteInstance {},
	texture_Wall10: class extends self.ITiledBackgroundInstance {},
	texture_Wall11: class extends self.ITiledBackgroundInstance {},
	texture_Wall13: class extends self.ITiledBackgroundInstance {},
	texture_Wall14: class extends self.ITiledBackgroundInstance {},
	texture_Wall15: class extends self.ITiledBackgroundInstance {},
	texture_Wall7: class extends self.ITiledBackgroundInstance {},
	texture_Wall8: class extends self.ITiledBackgroundInstance {},
	texture_Wall9: class extends self.ITiledBackgroundInstance {},
	texture_Wall12: class extends self.ITiledBackgroundInstance {},
	Vending_sprite1: class extends self.ISpriteInstance {},
	Vending_sprite2: class extends self.ISpriteInstance {},
	VendingBorder_sprite: class extends self.ISpriteInstance {},
	Vending_sprite3: class extends self.ISpriteInstance {},
	texture_Wall16: class extends self.ITiledBackgroundInstance {},
	texture_Wall17: class extends self.ITiledBackgroundInstance {},
	texture_Wall18: class extends self.ITiledBackgroundInstance {},
	texture_Wall19: class extends self.ITiledBackgroundInstance {},
	texture_Wall20: class extends self.ITiledBackgroundInstance {},
	Vending_sprite4: class extends self.ISpriteInstance {},
	Decorations: class extends self.I3DModelInstance {},
	Carpet: class extends self.ISpriteInstance {},
	Trees: class extends self.ISpriteInstance {},
	FakeWall: class extends self.I3DShapeInstance {},
	Banners: class extends self.ISpriteInstance {},
	Paintings: class extends self.ISpriteInstance {},
	_3D_Player: class extends self.ISpriteInstance {},
	_3D_Camera: class extends self.ISpriteInstance {},
	_3D_PlayerRange: class extends self.ISpriteInstance {},
	PlayerLight: class extends self.I3DLightInstance {},
	PlayerModel: class extends self.I3DModelInstance {},
	Faces: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	PlayerModel1: class extends self.I3DModelInstance {},
	PlayerModel2: class extends self.I3DModelInstance {},
	PlayerModel3: class extends self.I3DModelInstance {},
	PlayerModel4: class extends self.I3DModelInstance {},
	Faces1: class extends self.ISpriteInstance {},
	Faces2: class extends self.ISpriteInstance {},
	Faces3: class extends self.ISpriteInstance {},
	Faces4: class extends self.ISpriteInstance {},
	_3D_Peer: class extends self.ISpriteInstance {},
	Item1: class extends self.ISpriteInstance {},
	Item2: class extends self.ISpriteInstance {},
	Item3: class extends self.ISpriteInstance {},
	Item4: class extends self.ISpriteInstance {},
	Body1: class extends self.ISpriteInstance {},
	Body2: class extends self.ISpriteInstance {},
	Body3: class extends self.ISpriteInstance {},
	Body4: class extends self.ISpriteInstance {},
	PlayerName: class extends self.ITextInstance {},
	MusicZones: class extends self.ISpriteInstance {},
	CumulativeZones: class extends self.ISpriteInstance {},
	TouchZones: class extends self.ISpriteInstance {},
	InventorySlot: class extends self.ISpriteInstance {},
	InventorySlotY: class extends self.ISpriteInstance {},
	HandAnimation: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	HUD_Interferences: class extends self.ISpriteInstance {},
	itemdescription: class extends self.ITextInstance {},
	ScreenText: class extends self.ITextInstance {},
	Puntatore: class extends self.ISpriteInstance {},
	Screen_CumulativeText: class extends self.ITextInstance {},
	AlertText: class extends self.ITextInstance {},
	HUD_SfondoMenu: class extends self.ISpriteInstance {},
	HUD_SfondoMenuPattern: class extends self.ITiledBackgroundInstance {},
	Menu_button: class extends self.ISpriteInstance {},
	Menu_Text: class extends self.ITextInstance {},
	SelectionPoint: class extends self.ISpriteInstance {},
	DebugMenu: class extends self.ISpriteInstance {},
	ModelPC: class extends self.I3DModelInstance {},
	HUD_Information: class extends self.ITextInstance {},
	Stamine: class extends self.ISpriteInstance {},
	CacioMagico: class extends self.ISpriteInstance {},
	InteractText: class extends self.ITextInstance {},
	ItemDescriptions: class extends self.IJSONInstance {},
	ItemGenerator: class extends self.ISpriteInstance {},
	ItemPool: class extends self.IInstance {},
	ItemPoolTables: class extends self.IJSONInstance {},
	Model_caciocavallo: class extends self.I3DModelInstance {},
	PlaceablePreview: class extends self.ISpriteInstance {},
	Model_glue: class extends self.I3DModelInstance {},
	Model_mantle: class extends self.I3DModelInstance {},
	portal1: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	Model_capricorno: class extends self.I3DModelInstance {},
	harpooncorda: class extends self.ISpriteInstance {},
	Model_trappola: class extends self.I3DModelInstance {},
	Gustavo: class extends self.ISpriteInstance {},
	M_Gustavo: class extends self.I3DModelInstance {},
	Path_Gustavo: class extends self.ISpriteInstance {},
	Fresco: class extends self.ISpriteInstance {},
	M_Fresco: class extends self.I3DModelInstance {},
	Path_Fresco: class extends self.ISpriteInstance {},
	Path_MrMorte: class extends self.ISpriteInstance {},
	MrMorte: class extends self.ISpriteInstance {},
	M_MrMorte: class extends self.I3DModelInstance {},
	Canerino: class extends self.ISpriteInstance {},
	M_Canerino: class extends self.I3DModelInstance {},
	Path_Canerino: class extends self.ISpriteInstance {},
	Pane: class extends self.ISpriteInstance {},
	Path_Pane: class extends self.ISpriteInstance {},
	M_Pane: class extends self.I3DModelInstance {},
	Nano: class extends self.ISpriteInstance {},
	M_Nano: class extends self.I3DModelInstance {},
	Path_Nano: class extends self.ISpriteInstance {},
	Manzone: class extends self.ISpriteInstance {},
	M_Manzone: class extends self.I3DModelInstance {},
	Path_Manzone: class extends self.ISpriteInstance {},
	M_Pantaleone: class extends self.I3DModelInstance {},
	JumpscareSprite: class extends self.ISpriteInstance {},
	DipintoTexture: class extends self.ISpriteInstance {},
	Modello_cornice: class extends self.I3DModelInstance {},
	door1: class extends self.I3DModelInstance {},
	DoorsCollision: class extends self.I3DShapeInstance {},
	PuzzleLock: class extends self.ISpriteInstance {},
	Elevator: class extends self.I3DModelInstance {},
	ElevatorDoor: class extends self.I3DShapeInstance {},
	InvisibleWall: class extends self.I3DShapeInstance {},
	MobilePainting: class extends self.I3DModelInstance {},
	NpcContainer: class extends self.ISpriteInstance {},
	Npc_body: class extends self.ISpriteInstance {},
	NpcDialogue: class extends self.ITextInstance {},
	DialogueBox: class extends self.ISpriteInstance {},
	NpcPositions: class extends self.ISpriteInstance {},
	HoverTypes: class extends self.ISpriteInstance {},
	HT_SlotGraphics: class extends self.ISpriteInstance {},
	HT_SlotLever: class extends self.ISpriteInstance {},
	HT_Slots: class extends self.ISpriteInstance {},
	HT_SlotSkip: class extends self.ISpriteInstance {},
	Ricalco: class extends self.ISpriteInstance {},
	StoricTitles: class extends self.ITextInstance {},
	TitlesDeco: class extends self.ISpriteInstance {},
	EndingBackground: class extends self.ITiledBackgroundInstance {},
	Camera3D: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PhotonRealtime: class extends C3.Plugins.ExitGames_PhotonRealtime.Instance {},
	FirebaseSDK: class extends C3.Plugins.Sparsha_FirebaseSDK.Instance {},
	FirebaseAuthBasic: class extends C3.Plugins.Sparsha_FirebaseAuth.Instance {},
	FirebaseRDBasic: class extends C3.Plugins.Sparsha_FirebaseRealtimeDatabase.Instance {},
	AJAX: class extends self.IInstance {},
	MonitorBorder: class extends self.ISpriteInstance {},
	MoitorEffect: class extends self.ITiledBackgroundInstance {},
	PC_Background: class extends self.ISpriteInstance {},
	PC_Cursor: class extends self.ISpriteInstance {},
	PC_Actionbar: class extends self.ITiledBackgroundInstance {},
	EmojiBoard: class extends self.ISpriteInstance {},
	AppIcon: class extends self.ISpriteInstance {},
	AppDownloadState: class extends self.ISpriteInstance {},
	PC_Cam: class extends self.ISpriteInstance {},
	LayerInteractivity: class extends C3.Plugins.Custom_LayerInteractivity.Instance {},
	Window_Notes_Text: class extends self.ITextInstance {},
	StartAnimation: class extends self.ISpriteInstance {},
	websitelink: class extends self.ITextInstance {},
	InternetElementsDeco: class extends self.ISpriteInstance {},
	ChangeFrameDeco: class extends self.ISpriteInstance {},
	websiteText: class extends self.ITextInstance {},
	Window: class extends self.I9PatchInstance {},
	WindowCore: class extends self.ISpriteInstance {},
	WindowButton: class extends self.ISpriteInstance {},
	WindowBackground: class extends self.ITiledBackgroundInstance {},
	WindowIcon: class extends self.ISpriteInstance {},
	WindowName: class extends self.ITextInstance {},
	WindowScrollPanel: class extends self.ITiledBackgroundInstance {},
	LinkButtons: class extends self.ISpriteInstance {},
	WindowMaskPanel: class extends self.ISpriteInstance {},
	VideoCanvas: class extends C3.Plugins.ClaudeUI_VideoCanvas.Instance {},
	window_Internal_button: class extends self.ISpriteInstance {},
	WindowDeco: class extends self.ISpriteInstance {},
	MPCF: class extends self.ISpriteInstance {},
	BuyPanel: class extends self.ISpriteInstance {},
	BuyButton: class extends self.ISpriteInstance {},
	ShopJson: class extends self.IJSONInstance {},
	GameButton: class extends self.ISpriteInstance {},
	HUD_overlay: class extends self.ISpriteInstance {},
	MenuText: class extends self.ITextInstance {},
	ButtonAnimation: class extends self.ISpriteInstance {},
	MenuButton: class extends self.ISpriteInstance {},
	AccountImage: class extends self.ISpriteInstance {},
	InteractiveText: class extends self.ITextInstance {},
	CharacterSelector: class extends self.ISpriteInstance {},
	VideoPanel: class extends self.ISpriteInstance {},
	SfidaText: class extends self.ITextInstance {},
	SfidaCompletata: class extends self.ISpriteInstance {},
	PlayersInfo: class extends self.IJSONInstance {},
	Transition: class extends self.ITiledBackgroundInstance {},
	BlackScreen: class extends self.ITiledBackgroundInstance {},
	AccenzionePc: class extends self.ITextInstance {},
	GameSave: class extends self.IJSONInstance {},
	ResocontoValue: class extends self.IJSONInstance {},
	Floors_and_roofs: class extends self.ITiledBackgroundInstance {},
	Walls: class extends self.I3DShapeInstance {},
	Structure: class extends self.I3DModelInstance {},
	pathfinding_obstacles: class extends self.I3DShapeInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Doors: class extends self.I3DModelInstance {},
	ItemModels_Placed: class extends self.I3DModelInstance {},
	MouseAnimation: class extends self.ISpriteInstance {},
	particular: class extends self.ISpriteInstance {},
	Peer: class extends self.ISpriteInstance {},
	Distinction: class extends self.ISpriteInstance {},
	DistinctionModel: class extends self.I3DModelInstance {}
}